#!/usr/bin/env bash
# Authored by Michael Hebelka <michael.hebelka@sharpspring.com>

: ${ARCH:=darwin_amd64}

if [[ $# < 1 ]]; then
    echo "Current version: terraform-$(basename $(readlink $(which terraform)))"
    echo "Usage: $(basename $0) <version>"
    exit 1
fi

mkdir -p ~/.tvm/versions

version=$1
exe_file=~/.tvm/versions/$version

if [ ! -f $exe_file ]; then
    tempfile=$(mktemp)
    trap 'rm -f "$tempfile"' EXIT

    curl https://releases.hashicorp.com/terraform/$version/terraform_${version}_${ARCH}.zip --output $tempfile
    unzip -p $tempfile terraform > $exe_file
    chmod +x $exe_file
fi

ln -sf $exe_file ~/.tvm/bin/terraform
